#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mockito-core
Version  : 2.21.0
Release  : 2
URL      : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.jar
Source0  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.jar
Source1  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-mockito-core-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-mockito-core package.
Group: Data

%description data
data components for the mvn-mockito-core package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.jar
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.pom
