#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mockito-core
Version  : 2.21.0
Release  : 4
URL      : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.jar
Source0  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.jar
Source1  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.pom
Source2  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.25.1/mockito-core-2.25.1.jar
Source3  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.25.1/mockito-core-2.25.1.pom
Source4  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.27.0/mockito-core-2.27.0.jar
Source5  : https://repo1.maven.org/maven2/org/mockito/mockito-core/2.27.0/mockito-core-2.27.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-mockito-core-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-mockito-core package.
Group: Data

%description data
data components for the mvn-mockito-core package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.25.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.25.1/mockito-core-2.25.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.25.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.25.1/mockito-core-2.25.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.27.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.27.0/mockito-core-2.27.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.27.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/mockito/mockito-core/2.27.0/mockito-core-2.27.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.jar
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.21.0/mockito-core-2.21.0.pom
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.25.1/mockito-core-2.25.1.jar
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.25.1/mockito-core-2.25.1.pom
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.27.0/mockito-core-2.27.0.jar
/usr/share/java/.m2/repository/org/mockito/mockito-core/2.27.0/mockito-core-2.27.0.pom
